package:
  name: helloworld
  version: 1.0.0

source:
  path: ..

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - conda-verify

  host:
    - python
    - setuptools
    - pytest==4.1.1
    - pytest-mock==1.10.0
    - numpy

  run:
    - python
    - pytest-mock==1.10.0
    - flask==1.0.2
    - flask-restful==0.3.6

test:
  source_files:
    - tests
  requires:
    - pytest
    - pytest-cov
    - pytest-runner
  commands:
    - pytest tests

about:
  home: https://github.com/Luke31/python-helloworld
  summary: Python Test project with conda and docker
